/**
 * Local companion memory (Phase 14).
 *
 * A tiny, deterministic record of *meaningful* interaction history — how often
 * the butterfly has been summoned, how many sessions it has shared, how long
 * it has been around — from which one small abstract fact is derived: how
 * familiar the companion has become with this person.
 *
 * What this module is deliberately NOT:
 *
 * - Not telemetry. Two event kinds exist (`session_start`, `summon`), counters
 *   are bounded, and nothing about cursor positions, frames, destinations or
 *   the desktop is ever recorded. A cursor parked on the butterfly produces
 *   no events at all — only clicks the butterfly actually answered count.
 * - Not a behavior authority. This module never imports the flight
 *   controller, the personality or the scene; it computes a `CompanionState`
 *   and the personality alone decides what familiarity means (see
 *   `applyFamiliarity` in `personality.ts`). The dependency arrow runs
 *   Interaction → Memory → CompanionState → Personality → FlightController,
 *   and never backwards.
 * - Not networked. Persistence is `localStorage` and nothing else: no fetch,
 *   no Tauri command, no analytics, no accounts. Memory never leaves the
 *   machine, and stores no application titles, URLs or window data — only
 *   counts and timestamps this application generated itself.
 *
 * Failure is always non-fatal: an unreadable or corrupt record falls back to
 * empty memory (which behaves exactly like a first launch), and a failed save
 * is swallowed. Losing memory costs familiarity, never correctness.
 *
 * `tools/check-desktop.mjs` enforces the boundaries above; the deterministic
 * suite in `tools/test-memory.mjs` covers the model, the thresholds, the
 * persistence seam and the failure paths.
 */

/** The storage schema version written with every record. */
export const MEMORY_VERSION = 1;
/** The single storage key the companion memory occupies. */
export const MEMORY_STORAGE_KEY = "butterfly.companion.memory";

/**
 * Bounds. Counters saturate instead of growing forever, so a long-lived
 * installation cannot produce absurd numbers — and every bound sits far above
 * the companion-state thresholds, so saturation can never freeze the state.
 */
export const MAX_SUMMONS = 10_000;
export const MAX_SESSIONS = 1_000;
/** ~1000 hours of recorded time together. */
export const MAX_TOGETHER_MS = 1_000 * 60 * 60 * 1000;
/**
 * One commit may never account for more than this, so a tab left open
 * overnight (or a clock that jumped) cannot fabricate days of togetherness.
 */
export const MAX_SESSION_STEP_MS = 4 * 60 * 60 * 1000;
/** Debounce between a memory event and its write: bursty, never per frame. */
export const SAVE_DELAY_MS = 1_000;

/**
 * The companion states, ordered by familiarity.
 *
 * Four names, no more: a creature you have just met, one you know, one that
 * is comfortable with you, one that is attached. This is familiarity, not a
 * score — there is no XP, no level, no reward and no decay. States are
 * derived from cumulative counters, so they only ever move forward, and only
 * `new → familiar` is reachable in a single sitting: everything past that
 * requires coming back in a later session, which is what makes the
 * progression feel like a relationship rather than a streak.
 */
export const COMPANION_STATES = ["new", "familiar", "comfortable", "attached"] as const;
export type CompanionState = (typeof COMPANION_STATES)[number];

/* --- State thresholds (all cumulative; explainable in one sentence each) --- */

/** `familiar`: at least this many answered summons, ever. */
export const FAMILIAR_SUMMONS = 5;
/** `comfortable`: this many summons *and* this many sessions... */
export const COMFORTABLE_SUMMONS = 25;
export const COMFORTABLE_SESSIONS = 3;
/** `attached`: sustained interaction across many sessions and minutes. */
export const ATTACHED_SUMMONS = 75;
export const ATTACHED_SESSIONS = 8;
export const ATTACHED_TOGETHER_MS = 10 * 60 * 1000;

/**
 * What is remembered. Six fields, all of them generated by this application
 * about its own interaction — never about the desktop around it.
 */
export interface MemoryState {
  /** Schema version (`MEMORY_VERSION`) of the record itself. */
  version: number;
  /** Application launches in which a session was opened. */
  sessions: number;
  /** Clicks that successfully summoned the butterfly. */
  summons: number;
  /** Committed wall-clock time spent in sessions (ms). */
  togetherMs: number;
  /** Epoch ms of the first remembered event; `0` = not yet known. */
  firstMetAt: number;
  /** Epoch ms of the most recent remembered event. */
  lastSeenAt: number;
}

/**
 * The entire event vocabulary. Two kinds, both discrete: a session opening,
 * and a click the butterfly actually flew to. Continuous observations
 * (cursor proximity, crowding, frames) are *personality's* short-term
 * business and are deliberately not part of memory.
 */
export type CompanionEvent = "session_start" | "summon";

/** Where a loaded record came from — never silently guessed. */
export type MemoryLoadSource =
  | "stored" // a valid record was read
  | "empty" // storage exists, nothing has been written yet
  | "invalid" // unreadable or out-of-range record → safe empty fallback
  | "unsupported-version" // written by a different schema → safe empty fallback
  | "unavailable"; // no usable storage at all → safe empty fallback

/** The minimal storage seam: `localStorage` satisfies it, so do test fakes. */
export interface MemoryStorage {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

/** A fresh record: exactly the behavior of a first launch. */
export function emptyMemory(): MemoryState {
  return {
    version: MEMORY_VERSION,
    sessions: 0,
    summons: 0,
    togetherMs: 0,
    firstMetAt: 0,
    lastSeenAt: 0,
  };
}

/** Monotonic rank of each state (`new` = 0), for ordering checks. */
export function companionRank(state: CompanionState): number {
  return COMPANION_STATES.indexOf(state);
}

/**
 * Applies one event. Pure: the same memory, event and timestamp always yield
 * the same result, and an unknown event or a nonsensical timestamp changes
 * nothing rather than corrupting the record.
 */
export function applyCompanionEvent(
  memory: MemoryState,
  event: CompanionEvent,
  now: number,
): MemoryState {
  const at = Number.isFinite(now) && now >= 0 ? now : memory.lastSeenAt;
  const stamped: Pick<MemoryState, "firstMetAt" | "lastSeenAt"> = {
    firstMetAt: memory.firstMetAt > 0 ? memory.firstMetAt : at,
    lastSeenAt: at,
  };
  switch (event) {
    case "session_start":
      return {
        ...memory,
        sessions: Math.min(memory.sessions + 1, MAX_SESSIONS),
        ...stamped,
      };
    case "summon":
      return {
        ...memory,
        summons: Math.min(memory.summons + 1, MAX_SUMMONS),
        ...stamped,
      };
    default:
      return memory;
  }
}

/**
 * Commits wall-clock time spent together since the previous commit. Pure and
 * defensive: no time passed, a backwards clock or an already-saturated total
 * all return the memory unchanged.
 */
export function commitElapsed(
  memory: MemoryState,
  committedAt: number,
  now: number,
): MemoryState {
  const elapsed = now - committedAt;
  if (!(elapsed > 0)) return memory;
  const step = Math.min(elapsed, MAX_SESSION_STEP_MS);
  const togetherMs = Math.min(memory.togetherMs + step, MAX_TOGETHER_MS);
  if (togetherMs === memory.togetherMs) return memory;
  return { ...memory, togetherMs };
}

/**
 * Derives the companion state. A pure function of the counters — no time, no
 * randomness, no hidden input — so the same memory always reads the same way,
 * the thresholds can be tested at their exact boundaries, and the state can
 * only ever move forward as the counters grow.
 */
export function deriveCompanionState(memory: MemoryState): CompanionState {
  if (
    memory.summons >= ATTACHED_SUMMONS &&
    memory.sessions >= ATTACHED_SESSIONS &&
    memory.togetherMs >= ATTACHED_TOGETHER_MS
  ) {
    return "attached";
  }
  if (memory.summons >= COMFORTABLE_SUMMONS && memory.sessions >= COMFORTABLE_SESSIONS) {
    return "comfortable";
  }
  if (memory.summons >= FAMILIAR_SUMMONS) return "familiar";
  return "new";
}

/**
 * Serializes exactly the six known fields — extra properties cannot leak into
 * storage, and the output is stable for a given record.
 */
export function serializeMemory(memory: MemoryState): string {
  return JSON.stringify({
    version: MEMORY_VERSION,
    sessions: memory.sessions,
    summons: memory.summons,
    togetherMs: memory.togetherMs,
    firstMetAt: memory.firstMetAt,
    lastSeenAt: memory.lastSeenAt,
  });
}

function isCount(value: unknown, max: number): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= max;
}

function isMemoryRecord(value: unknown): value is MemoryState {
  if (typeof value !== "object" || value === null) return false;
  const record = value as Record<string, unknown>;
  const finiteTime = (v: unknown) =>
    typeof v === "number" && Number.isFinite(v) && v >= 0;
  return (
    record.version === MEMORY_VERSION &&
    isCount(record.sessions, MAX_SESSIONS) &&
    isCount(record.summons, MAX_SUMMONS) &&
    typeof record.togetherMs === "number" &&
    Number.isFinite(record.togetherMs) &&
    record.togetherMs >= 0 &&
    record.togetherMs <= MAX_TOGETHER_MS &&
    finiteTime(record.firstMetAt) &&
    finiteTime(record.lastSeenAt) &&
    (record.firstMetAt as number) <= (record.lastSeenAt as number)
  );
}

/**
 * Parses a stored record defensively. Anything unreadable, wrongly shaped or
 * out of range falls back to empty memory rather than throwing or partially
 * loading — a corrupt file costs familiarity, never a working companion.
 * A record from a *different* schema version is reported as such and also
 * falls back: merging an unknown schema would be guessing.
 */
export function parseMemory(raw: string | null | undefined): {
  memory: MemoryState;
  source: MemoryLoadSource;
} {
  if (raw === null || raw === undefined || raw === "") {
    return { memory: emptyMemory(), source: "empty" };
  }
  let value: unknown;
  try {
    value = JSON.parse(raw);
  } catch {
    return { memory: emptyMemory(), source: "invalid" };
  }
  if (typeof value !== "object" || value === null) {
    return { memory: emptyMemory(), source: "invalid" };
  }
  const version = (value as Record<string, unknown>).version;
  if (typeof version === "number" && Number.isFinite(version) && version !== MEMORY_VERSION) {
    return { memory: emptyMemory(), source: "unsupported-version" };
  }
  if (!isMemoryRecord(value)) {
    return { memory: emptyMemory(), source: "invalid" };
  }
  return {
    memory: {
      version: value.version,
      sessions: value.sessions,
      summons: value.summons,
      togetherMs: value.togetherMs,
      firstMetAt: value.firstMetAt,
      lastSeenAt: value.lastSeenAt,
    },
    source: "stored",
  };
}

/** Loads through the storage seam. Never throws; absence is not an error. */
export function loadMemory(storage: MemoryStorage | null): {
  memory: MemoryState;
  source: MemoryLoadSource;
} {
  if (!storage) return { memory: emptyMemory(), source: "unavailable" };
  try {
    return parseMemory(storage.getItem(MEMORY_STORAGE_KEY));
  } catch {
    return { memory: emptyMemory(), source: "unavailable" };
  }
}

/** Saves through the storage seam. Never throws; reports success only. */
export function saveMemory(memory: MemoryState, storage: MemoryStorage | null): boolean {
  if (!storage) return false;
  try {
    storage.setItem(MEMORY_STORAGE_KEY, serializeMemory(memory));
    return true;
  } catch {
    // Quota, private mode, disabled storage: the session continues without
    // persistence. Persistence failure is never a fatal application error.
    return false;
  }
}

/**
 * The browser's `localStorage` if one exists — the only persistence this
 * feature uses, present in both the web build and the Tauri WebView. Access
 * itself can throw (storage disabled), so it is guarded.
 */
function browserMemoryStorage(): MemoryStorage | null {
  try {
    return (globalThis as { localStorage?: MemoryStorage }).localStorage ?? null;
  } catch {
    return null;
  }
}

export interface CompanionMemoryOptions {
  /** Defaults to `localStorage` when present; `null` forces "no storage". */
  storage?: MemoryStorage | null;
  /** Clock, injectable for deterministic tests. */
  now?: () => number;
  /**
   * Debounce scheduler, injectable for deterministic tests. Returns a
   * cancellation function. The default is a one-shot `setTimeout` — there is
   * deliberately no interval and no polling anywhere in this module.
   */
  schedule?: (fn: () => void, delayMs: number) => () => void;
}

function defaultSchedule(fn: () => void, delayMs: number): () => void {
  const id = setTimeout(fn, delayMs);
  return () => clearTimeout(id);
}

/**
 * The runtime face of the memory: holds the current record, applies events,
 * and persists them debounced.
 *
 * Deliberately small. Session start is idempotent (React StrictMode runs
 * effects twice, and a session must count once), writes are coalesced into at
 * most one pending save, and `flush()` commits elapsed time and writes
 * immediately — the best-effort path used on page hide. Nothing here runs per
 * frame, and no method can throw: a broken storage seam degrades to "memory
 * does not persist", never to a crashed companion.
 */
export class CompanionMemory {
  private readonly storage: MemoryStorage | null;
  private readonly now: () => number;
  private readonly schedule: (fn: () => void, delayMs: number) => () => void;
  private memory: MemoryState;
  private committedAt: number;
  private source: MemoryLoadSource;
  private sessionStarted = false;
  private cancelScheduled: (() => void) | null = null;

  constructor(options: CompanionMemoryOptions = {}) {
    this.storage =
      options.storage !== undefined ? options.storage : browserMemoryStorage();
    this.now = options.now ?? (() => Date.now());
    this.schedule = options.schedule ?? defaultSchedule;
    const loaded = loadMemory(this.storage);
    this.memory = loaded.memory;
    this.source = loaded.source;
    this.committedAt = this.now();
  }

  /** A copy of the record, safe to read at any time. */
  get snapshot(): MemoryState {
    return { ...this.memory };
  }

  /** The companion state derived from the record. */
  get state(): CompanionState {
    return deriveCompanionState(this.memory);
  }

  /** Where the initial record came from (stored / empty / invalid / ...). */
  get loadSource(): MemoryLoadSource {
    return this.source;
  }

  /**
   * Opens this launch's session. Idempotent: repeated calls (effect
   * re-runs, remounts) count exactly one session.
   */
  beginSession(): void {
    if (this.sessionStarted) return;
    this.sessionStarted = true;
    const now = this.now();
    this.memory = applyCompanionEvent(this.memory, "session_start", now);
    this.committedAt = now;
    this.scheduleSave();
  }

  /**
   * Records one *answered* summon — a click the butterfly actually flew to.
   * This is the only per-interaction growth path; stationary presence and
   * cursor movement never reach this module.
   */
  recordSummon(): void {
    this.memory = applyCompanionEvent(this.memory, "summon", this.now());
    this.scheduleSave();
  }

  /** Commits elapsed time and persists now. Cancellably debounced. */
  flush(): boolean {
    if (this.cancelScheduled) {
      this.cancelScheduled();
      this.cancelScheduled = null;
    }
    return this.save();
  }

  /** Cancels any pending write without saving (unmount after an explicit flush). */
  dispose(): void {
    if (this.cancelScheduled) {
      this.cancelScheduled();
      this.cancelScheduled = null;
    }
  }

  /** Coalesces bursts: at most one write is ever pending. */
  private scheduleSave(): void {
    if (this.cancelScheduled) return;
    this.cancelScheduled = this.schedule(() => {
      this.cancelScheduled = null;
      this.save();
    }, SAVE_DELAY_MS);
  }

  private save(): boolean {
    const now = this.now();
    this.memory = commitElapsed(this.memory, this.committedAt, now);
    this.committedAt = now;
    return saveMemory(this.memory, this.storage);
  }
}
