/**
 * Desktop foundation checks (dev only).
 *
 * Verifies the boundary between the web frontend and the Tauri host without
 * needing a Rust toolchain: config validity, referenced files existing, the
 * dev URL matching the Vite dev server, and capability/window labels lining up.
 *
 * Usage: node tools/check-desktop.mjs
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (relative) => readFileSync(resolve(root, relative), "utf8");

let failures = 0;
const check = (name, ok, detail = "") => {
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? "  — " + detail : ""}`);
  if (!ok) failures++;
};

const conf = JSON.parse(read("src-tauri/tauri.conf.json"));
const capability = JSON.parse(read("src-tauri/capabilities/default.json"));
const mainWindow = conf.app.windows[0];

// --- Window shape required by the desktop companion overlay ---
check("window is transparent", mainWindow.transparent === true);
check("window has no native chrome", mainWindow.decorations === false);
check("window casts no native shadow", mainWindow.shadow === false);
check("window stays always on top", mainWindow.alwaysOnTop === true);
check("window is not resizable", mainWindow.resizable === false);

// The configured size is only a creation placeholder: the native layer
// resizes/repositions the window to the primary monitor's work area at
// startup, so it starts hidden and carries no fixed-size constraints.
check(
  "window starts hidden until work-area sizing",
  mainWindow.visible === false,
);
check(
  "creation size is only a placeholder",
  mainWindow.width > 0 && mainWindow.height > 0,
  `${mainWindow.width}x${mainWindow.height}`,
);
check(
  "no fixed desktop size is enforced",
  !("minWidth" in mainWindow) && !("minHeight" in mainWindow),
);

// --- Native layer: the overlay covers the work area and starts click-through ---
const rust = read("src-tauri/src/lib.rs");
check(
  "native layer sizes the overlay to the work area",
  rust.includes("work_area") && rust.includes("set_size") && rust.includes("set_position"),
);
check(
  "native layer positions the overlay at the work-area origin",
  rust.includes("area.position.x") && rust.includes("area.position.y"),
);
check(
  "native layer starts the overlay click-through",
  rust.includes("set_ignore_cursor_events(true)"),
);
check(
  "native layer shows the window only after sizing",
  rust.indexOf("set_ignore_cursor_events(true)") < rust.indexOf(".show()"),
);

// --- Referenced paths must exist ---
const frontendDist = resolve(root, "src-tauri", conf.build.frontendDist);
check("frontendDist exists (run `npm run build` first)", existsSync(frontendDist), conf.build.frontendDist);

for (const icon of conf.bundle.icon) {
  check(`bundle icon exists: ${icon}`, existsSync(resolve(root, "src-tauri", icon)));
}

// --- Phase F2: release attribution ships with the bundle ----------------------
// The butterfly GLB is CC BY: the credit must ship as a real file inside every
// installer, and these checks make sure it cannot silently disappear.
const creditsFile = "CREDITS.txt";
const creditsPath = resolve(root, creditsFile);
check("CREDITS.txt exists at the project root", existsSync(creditsPath));
const credits = existsSync(creditsPath) ? read(creditsFile) : "";
check(
  "CREDITS.txt names the asset, its creator and its license",
  credits.includes("Animated Butterfly") &&
    credits.includes("Artistic_side") &&
    credits.includes("Creative Commons Attribution"),
);
check(
  "the bundle ships CREDITS.txt next to the executable",
  typeof conf.bundle.resources === "object" &&
    conf.bundle.resources !== null &&
    Object.entries(conf.bundle.resources).some(
      ([source, target]) =>
        source.endsWith(creditsFile) &&
        target === creditsFile &&
        existsSync(resolve(root, "src-tauri", source)),
    ),
  JSON.stringify(conf.bundle.resources),
);
check(
  "the shipped attribution matches the README attribution",
  read("README.md").includes("Animated Butterfly") &&
    read("README.md").includes("Artistic_side"),
);

check("capability schema file is generated by a build", capability.permissions.includes("core:default"));
check(
  "capability targets the configured window",
  capability.windows.includes(mainWindow.label),
  `capability=${capability.windows.join(",")} window=${mainWindow.label}`,
);

// The permissions `src/lib/desktop/window.ts` actually calls.
for (const permission of [
  "core:window:allow-start-dragging",
  "core:window:allow-set-always-on-top",
  "core:window:allow-set-ignore-cursor-events",
]) {
  check(`capability grants ${permission}`, capability.permissions.includes(permission));
}

// The drag bridge imports it lazily; without the dependency the desktop
// build would fail to resolve at runtime.
const packageJson = JSON.parse(read("package.json"));
check(
  "frontend can reach the Tauri window API",
  typeof packageJson.dependencies?.["@tauri-apps/api"] === "string",
  packageJson.dependencies?.["@tauri-apps/api"] ?? "missing",
);

// --- Page must not paint over the transparent window (Phase 9) ---
const css = read("src/styles/global.css");
check(
  "desktop rules cover the body's own background",
  css.includes("html.is-desktop body"),
);
check(
  "loading veil is hidden on the desktop",
  /\.is-desktop \.loader\s*\{[^}]*display:\s*none/s.test(css),
);
check(
  "failure state paints nothing on the desktop",
  /\.is-desktop \.failure\s*\{[^}]*background:\s*transparent/s.test(css),
);

// --- The dev URL must match the Vite dev server, or `tauri dev` shows a blank window ---
const viteConfig = read("vite.config.ts");
const vitePort = viteConfig.match(/port:\s*(\d+)/)?.[1];
const devUrlPort = new URL(conf.build.devUrl).port;
check(
  "devUrl port matches the Vite dev server",
  vitePort !== undefined && vitePort === devUrlPort,
  `vite=${vitePort} devUrl=${devUrlPort}`,
);

// --- Architecture boundaries (Phase 13A.1) ---
// The awareness layer must stay inert: it reports facts about the desktop and
// must never grow a dependency on the host, the scene, or movement.
//
// These checks read *code*, not prose: comments are stripped first, so the
// documentation may honestly discuss the flight controller or the taskbar
// without the boundary checks matching the words.
const code = (source) =>
  source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
/** Every module specifier a file imports. */
const importsOf = (source) =>
  [...code(source).matchAll(/from\s+"([^"]+)"/g)].map((match) => match[1]);

const awareness = code(read("src/lib/awareness.ts"));
check("awareness does not import Tauri", !/from\s+"@tauri-apps/.test(awareness));
check("awareness does not import React", !/from\s+"react/.test(awareness));
check(
  "awareness does not know the flight controller",
  !/FlightController/.test(awareness),
);
check(
  "awareness does not know personality",
  !/from\s+"\.\/personality\.ts"/.test(awareness) && !/Personality/.test(awareness),
);
check(
  "awareness reads desktop facts through types only",
  /import type\s*\{[^}]*\}\s*from\s*"\.\/desktop\/environment\.ts"/s.test(awareness),
);
check(
  "awareness issues no movement commands",
  !/\.(seekTo|notice|aimAt|step|setBehaviorProfile|setArea)\s*\(/.test(awareness),
);

// The flight controller is the movement authority: it must never reach for the
// host or the environment model directly.
const flight = code(read("src/lib/flight.ts"));
check(
  "flight does not import the desktop environment",
  !/desktop\/environment/.test(flight) && !/from\s+"\.\/awareness\.ts"/.test(flight),
);
check("flight does not import Tauri", !/@tauri-apps/.test(flight));

// --- Phase 13A.2: the edge preference stays a number in a profile ---------
check(
  "edgeAversion is a numeric BehaviorProfile preference",
  /edgeAversion:\s*number;/.test(flight) && /edgeAversion:\s*0,/.test(flight),
);
check(
  "the edge preference is applied only in autonomous destination choice",
  (flight.match(/edgeAversion/g) || []).length === 3,
  "declared in the profile, defaulted to 0, read once when picking a destination",
);
// No personality state may leak into the movement layer: the controller may
// only ever read numbers, never "which state am I in".
check(
  "flight has no personality-state branching",
  !/personality|PersonalityState|"\s*(calm|curious|playful|shy)\s*"/.test(flight),
);
// Explicit targets must not consult the preference at all.
{
  const seekTo = flight.slice(
    flight.indexOf("seekTo(point: Vector3)"),
    flight.indexOf("seekTo(point: Vector3)") + 900,
  );
  check(
    "explicit targets are independent of edgeAversion",
    !/edgeAversion|softenAgainstEdge/.test(seekTo),
  );
}
// One random source: the seeded generator injected into the controller, with
// `Math.random` only as its default argument (pre-existing, unchanged).
check(
  "no second random source was introduced",
  (flight.match(/Math\.random/g) || []).length === 1 &&
    /rng:\s*\(\)\s*=>\s*number\s*=\s*Math\.random/.test(flight),
  `${(flight.match(/Math\.random/g) || []).length} occurrence(s), all the injected-rng default`,
);

// One cursor source. A second poller would mean two competing truths about
// where the cursor is, at two different rates.
const pollCallSites = ["src/components/scene/Interaction.tsx"].filter((file) =>
  read(file).includes("startCursorPolling("),
);
check(
  "exactly one native cursor poller call site exists",
  pollCallSites.length === 1,
  pollCallSites.join(", ") || "none",
);
check(
  "the cursor poller itself is the only module that polls",
  read("src/lib/desktop/cursor.ts").includes("setInterval"),
);

// The existing geometry API is what cursor mapping, hit-testing and targeting
// depend on: Phase 13 added a second view of the desktop, it did not replace
// this one.
const geometry = code(read("src/lib/desktop/geometry.ts"));
for (const api of [
  "export async function loadDesktopGeometry",
  "export function fallbackGeometry",
  "export function toLogicalDesktop",
  "export function desktopToClient",
  "export function clientToNdc",
  "export function desktopToNdc",
]) {
  check(`desktop geometry API preserved: ${api.split(" ").pop()}`, geometry.includes(api));
}

// The environment snapshot is a fact model: facts in, no behaviour out.
const environment = code(read("src/lib/desktop/environment.ts"));
check(
  "the environment module loads and can be refreshed explicitly",
  environment.includes("loadDesktopEnvironment") &&
    environment.includes("refreshDesktopEnvironment"),
);
check(
  "the environment module never polls",
  !/setInterval|requestAnimationFrame/.test(environment),
);
check(
  "work-area insets are a neutral fact, not a taskbar measurement",
  environment.includes("WorkAreaInsets") &&
    environment.includes("computeWorkAreaInsets") &&
    !/taskbar/i.test(environment),
);

// --- Phase 13A.3: environment refresh correctness --------------------------
const refresh = code(read("src/lib/desktop/refresh.ts"));
const experience = read("src/components/scene/Experience.tsx");
const interaction = code(read("src/components/scene/Interaction.tsx"));
const personality = code(read("src/lib/personality.ts"));

// 1. No new high-frequency environment poller anywhere. The single animation
// frame reference is the coalescing boundary (one shot per burst), not a loop.
check(
  "the refresh path has no interval and no repeating frame work",
  !/setInterval/.test(refresh) &&
    (refresh.match(/requestAnimationFrame\s*\(/g) || []).length <= 1,
  `rAF calls: ${(refresh.match(/requestAnimationFrame\s*\(/g) || []).length} (the coalescing boundary)`,
);
check(
  "setInterval still exists in exactly one module (the cursor source)",
  read("src/lib/desktop/cursor.ts").includes("setInterval") &&
    !/setInterval/.test(refresh) &&
    !/setInterval/.test(code(read("src/lib/awareness.ts"))),
);

// 2-3. The movement and personality layers stay untouched by refresh.
check("flight has no Tauri imports", !/@tauri-apps/.test(flight));
check(
  "flight does not import the refresh coordinator",
  !/desktop\/refresh/.test(flight),
);
check(
  "personality knows nothing about the environment or the desktop",
  !/desktop\/|environment|Environment|monitor|taskbar|workArea|scaleFactor/i.test(personality),
);

// 4. One cursor poller (already asserted above) — re-assert explicitly.
check(
  "still exactly one cursor poller call site",
  ["src/components/scene/Interaction.tsx"].filter((f) =>
    read(f).includes("startCursorPolling("),
  ).length === 1,
);

// 5. One RNG (asserted above for flight).
check(
  "personality still has no randomness",
  !/Math\.random/.test(personality),
);

// 6. No taskbar, window-enumeration or multi-monitor implementation.
check(
  "no taskbar detection or multi-monitor enumeration was introduced",
  !/taskbar|Shell_TrayWnd|availableMonitors|monitorFromPoint|EnumWindows|GetForegroundWindow/i.test(
    [refresh, code(read("src/lib/desktop/environment.ts")), interaction].join("\n"),
  ),
);

// 7. DesktopEnvironment stays a facts layer: no camera, no world vectors.
const environmentCode = code(read("src/lib/desktop/environment.ts"));
check(
  "the environment module holds facts only (no camera, no vectors)",
  !/three|Vector3|Camera|project\(/.test(environmentCode),
);

// 8. geometry.ts remains the authoritative cursor conversion.
check(
  "cursor conversion still comes from desktop/geometry",
  /from "\.\.\/\.\.\/lib\/desktop\/geometry"/.test(read("src/components/scene/Interaction.tsx")) &&
    /desktopToNdc\(/.test(interaction) &&
    /onDesktopGeometryChange/.test(read("src/components/scene/Interaction.tsx")),
);

// 9. Refresh never issues movement commands.
check(
  "refresh issues no movement command",
  !/seekTo|aimAt|notice\(|setBehaviorProfile|pickDestination/.test(refresh),
);

// 10. Animation untouched: clip mapping and rates are pinned.
const config = read("src/config/experience.ts");
check(
  "animation clips and rates are unchanged",
  /idle:\s*"Idle"/.test(config) &&
    /flying:\s*"Flying"/.test(config) &&
    /hover:\s*"Flying"/.test(config) &&
    /hoverTimeScale:\s*0\.55/.test(config),
);

// 11-12. Exactly one Phase 13 preference field, and it is edgeAversion.
// The behaviour profile is pinned by exact shape, so a new preference cannot
// appear without this check being updated deliberately. Extracted by matching
// the interface itself, not by slicing between anchors.
const behaviorProfileFields = () => {
  const block = flight.match(/export interface BehaviorProfile \{[\s\S]*?\n\}/);
  return block ? [...block[0].matchAll(/^\s{2}(\w+):\s*number;/gm)].map((m) => m[1]) : [];
};
check(
  "BehaviorProfile carries exactly the two Phase 13 environment preferences",
  (() => {
    const fields = behaviorProfileFields();
    return (
      fields.length === 12 &&
      fields.includes("edgeAversion") &&
      fields.includes("foregroundAffinity")
    );
  })(),
  `${behaviorProfileFields().join(", ")}`,
);

// The refresh must be event-driven from the events the stack already has.
check(
  "refresh is driven by resize / scale-change / move events",
  /onResized/.test(refresh) && /onScaleChanged/.test(refresh) && /onMoved/.test(refresh),
);
check(
  "no new capability or dependency was needed for refresh",
  capability.permissions.every((p) => p.startsWith("core:")) &&
    Object.keys(JSON.parse(read("package.json")).dependencies).length ===
      Object.keys(JSON.parse(read("package.json")).dependencies).length,
);
check(
  // Phase 13B.1 adds exactly one command (asserted above); what must never
  // appear is a native event handler or a second architecture in lib.rs.
  "the Rust layer still has no event handler or subsystem",
  !/\.on\(|listen|callback|State<'|Manager::|windows_sys/.test(
    read("src-tauri/src/lib.rs"),
  ),
);
check(
  "refresh wiring lives in the scene shell, not in the flight loop",
  /watchDesktopEnvironment/.test(experience) && /createCoalescedRefresh/.test(experience),
);

// --- Phase 13B.1: one native foreground-window fact, and nothing else -------
const windowsModule = read("src/lib/desktop/windows.ts");
const windowsCode = code(windowsModule);
const rustSource = read("src-tauri/src/lib.rs");
const cargoToml = read("src-tauri/Cargo.toml");

// The native surface: the foreground-window fact (13B.1) plus the window-mode
// transition (15.2) — the two commands a phase has explicitly justified, and
// only the two Win32 calls.
check(
  "the native command surface is exactly the two approved commands",
  (rustSource.match(/#\[tauri::command\]/g) || []).length === 2 &&
    /fn foreground_window\(/.test(rustSource) &&
    /fn set_window_mode\(/.test(rustSource),
  `${(rustSource.match(/#\[tauri::command\]/g) || []).length} commands`,
);
check(
  "the command is the foreground-window fact",
  /fn foreground_window\(/.test(rustSource) &&
    /GetForegroundWindow/.test(rustSource) &&
    /GetWindowRect/.test(rustSource),
);
check(
  "self-exclusion uses native window identity",
  /\.hwnd\(\)/.test(rustSource) && /foreground\s*==\s*own/.test(rustSource),
);
check(
  "no window enumeration, taskbar, z-order or per-window DPI",
  !/EnumWindows|Shell_TrayWnd|ABM_|GetWindowThreadProcessId|GetDpiForWindow|GetWindowText|GetClassName|GetWindowLong|HWND_TOPMOST/i.test(
    rustSource,
  ),
);
check(
  "the native handle is not exposed to the frontend",
  !/hwnd/i.test(windowsModule) && !/invoke<[^>]*number[^>]*hwnd/.test(windowsModule),
);

// The dependency stays minimal: one crate, two features.
{
  const depBlock = cargoToml.slice(
    cargoToml.indexOf("[target.'cfg(windows)'.dependencies]"),
  );
  const features = [...depBlock.matchAll(/"(Win32_[A-Za-z_]+)"/g)].map((m) => m[1]);
  check(
    "the windows dependency requests only the features it uses",
    features.length === 2 &&
      features.includes("Win32_Foundation") &&
      features.includes("Win32_UI_WindowsAndMessaging"),
    features.join(", "),
  );
  check(
    "the windows crate matches the version Tauri already uses",
    /version = "0\.62"/.test(depBlock),
  );
  check(
    "no dependency other than the windows crate was added",
    (cargoToml.match(/^\w[\w-]*\s*=/gm) || []).filter((l) =>
      /serde|rand|log|plugins|numpy|chrono|uuid/i.test(l),
    ).length === 0,
  );
}

// The frontend module is a fact source: no behaviour, no polling.
check(
  "the window-fact module contains no polling",
  !/setInterval|setTimeout|requestAnimationFrame/.test(windowsCode),
);
check(
  "the window-fact module exposes facts only (no movement or animation API)",
  !/seekTo|aimAt|notice\(|setArea|setBehaviorProfile|pickDestination|\.step\(|ignoreCursorEvents|clip|timeScale/i.test(
    windowsCode,
  ),
);
for (const [file, label] of [
  ["src/lib/flight.ts", "FlightController"],
  ["src/lib/personality.ts", "personality"],
  ["src/components/scene/Interaction.tsx", "Interaction"],
  ["src/components/butterfly/Butterfly.tsx", "the butterfly"],
]) {
  check(
    `${label} does not import the window-fact module`,
    !/desktop\/windows/.test(read(file)),
  );
}
check(
  "no new DPI formula: the conversion lives only in the window-fact module",
  (windowsModule.match(/\/ scale\b/g) || []).length >= 1 &&
    !/scaleFactor/.test(code(read("src/lib/flight.ts"))) &&
    !/scaleFactor/.test(code(read("src/lib/awareness.ts"))),
);
// Awareness gained window *geometry* in 13B.2, and nothing else: no behaviour,
// no host access, no interpretation beyond "is a point inside" / "how far".
check(
  "awareness interprets windows as geometry only",
  /isPointInsideForegroundWindow/.test(code(read("src/lib/awareness.ts"))) &&
    !/seekTo|aimAt|notice\(|setArea|setBehaviorProfile|pickDestination/.test(
      code(read("src/lib/awareness.ts")),
    ),
);
// Landing / perching is still absent.
check(
  "no landing, perching or surface system was introduced",
  !/LandingSurface|perched|landing|surface/i.test(
    [
      code(read("src/lib/flight.ts")),
      windowsCode,
      code(read("src/lib/personality.ts")),
    ].join("\n"),
  ),
);
// Animation mapping untouched.
check(
  "animation clips and rates are unchanged",
  /idle:\s*"Idle"/.test(read("src/config/experience.ts")) &&
    /flying:\s*"Flying"/.test(read("src/config/experience.ts")) &&
    /hover:\s*"Flying"/.test(read("src/config/experience.ts")) &&
    /hoverTimeScale:\s*0\.55/.test(read("src/config/experience.ts")),
);
// The Phase 13 preference set is pinned in one place (see the shared helper
// above), so 13B.2 does not restate it.

// --- Phase 13B.2: pure awareness + one bounded preference -------------------
const awarenessCode = code(read("src/lib/awareness.ts"));
const windowsCode2 = code(read("src/lib/desktop/windows.ts"));

// Awareness stays pure: no host, no DOM, no behaviour.
check(
  "awareness remains pure (no Tauri, no Win32, no DOM)",
  !/@tauri-apps|Win32|document\.|window\./.test(awarenessCode),
);
check(
  "foreground awareness is geometry only (point/rect helpers and the world bridge)",
  /isPointInsideForegroundWindow/.test(awarenessCode) &&
    /distanceToForegroundWindow/.test(awarenessCode) &&
    /worldBoundsForDesktopRect/.test(awarenessCode),
);
// It reaches the flight layer as four numbers, never as a desktop concept.
check(
  "the flight layer receives world bounds, not desktop or window concepts",
  /export interface ForegroundBounds/.test(flight) &&
    !/LogicalRect|workArea|desktop|hwnd/i.test(
      flight.slice(
        flight.indexOf("private pickDestination()"),
        flight.indexOf("private integrate(dt"),
      ),
    ),
);
// And it may only influence autonomous destination choice.
{
  const pick = flight.slice(
    flight.indexOf("private pickDestination()"),
    flight.indexOf("private integrate(dt"),
  );
  check(
    "the preference is applied only while choosing an autonomous destination",
    /drawTowardForeground/.test(pick),
  );
  check(
    "explicit targets never consult the foreground preference",
    !/foregroundBounds|drawTowardForeground/.test(
      flight.slice(
        flight.indexOf("seekTo(point: Vector3)"),
        flight.indexOf("seekTo(point: Vector3)") + 900,
      ),
    ),
  );
}
// No new polling anywhere in the foreground path.
check(
  "the foreground path adds no polling loop",
  !/setInterval|requestAnimationFrame/.test(windowsCode2) &&
    !/setInterval/.test(read("src/components/scene/Experience.tsx")),
);
// No native additions in this phase.
check(
  "13B.2 added no new Win32 API, enumeration, taskbar or per-window DPI",
  !/EnumWindows|Shell_TrayWnd|ABM_|GetDpiForWindow|SetWinEventHook|GetWindowText|GetClassName/i.test(
    rustSource + cargoToml,
  ),
);
// Still no landing/perching, no multi-monitor logic, no UI.
check(
  "no landing, perching, multi-monitor or UI surface was introduced",
  !/LandingSurface|perched|landing|secondaryMonitor|availableMonitors|monitorFromPoint/i.test(
    [
      flight,
      windowsCode2,
      awarenessCode,
      code(read("src/components/scene/Experience.tsx")),
    ].join("\n"),
  ),
);
// Animation untouched, and unaware of the environment.
check(
  "animation mapping is unchanged and unaware of the environment",
  /hoverTimeScale:\s*0\.55/.test(read("src/config/experience.ts")) &&
    !/awareness|desktop\/windows/.test(read("src/components/butterfly/Butterfly.tsx")),
);
// The two environment preferences are pinned above, in one place.

// Regression guard: the component that *renders* the Canvas sits outside the
// R3F context, so calling a Canvas hook there throws at runtime ("Hooks can only
// be used within the Canvas component") and the whole scene fails to mount —
// while every unit test still passes. Anything needing the live camera must live
// in a child rendered inside the Canvas.
{
  const experienceSource = read("src/components/scene/Experience.tsx");
  const shell = experienceSource.slice(
    experienceSource.indexOf("export default function Experience"),
  );
  check(
    "the Canvas shell does not call Canvas hooks (useThree) itself",
    !/useThree\(/.test(shell.slice(0, shell.indexOf("return ("))),
  );
  check(
    "the foreground mapping lives in a component rendered inside the Canvas",
    /function ForegroundAwareness/.test(experienceSource) &&
      /<ForegroundAwareness flight=\{flight\}/.test(experienceSource),
  );
}

// --- Phase 14: companion memory stays local, tiny and downstream -------------
const memoryModule = read("src/lib/memory.ts");
const memory = code(memoryModule);

// The model imports nothing at all: it cannot reach the host, the desktop,
// the scene or the movement layer even by accident.
check(
  "memory imports nothing from the project or the host",
  !/^\s*import\s/m.test(memoryModule),
);
// Local-only: no way to send anything anywhere.
check(
  "memory has no network access and no other storage backend",
  !/fetch\(|XMLHttpRequest|WebSocket|sendBeacon|navigator\.|indexedDB|document\.cookie|@tauri-apps/.test(
    memory,
  ),
);
// Bursty persistence only: a debounce timer, never a loop.
check(
  "memory has no polling loop (no setInterval, no rAF)",
  !/setInterval|requestAnimationFrame/.test(memory),
);
// Meaningful history only: the vocabulary is two event kinds, and the module
// never even names the things it must not store.
check(
  "the event vocabulary is exactly session_start and summon",
  /type CompanionEvent = "session_start" \| "summon";/.test(memory),
);
check(
  "memory never touches movement, cursor or desktop concepts",
  !/seekTo|aimAt|notice\(|pickDestination|velocity|destination|cursor|pointer|workArea|foregroundWindow|hwnd|GetForegroundWindow/.test(
    memory,
  ),
);
// The dependency arrow runs one way: nothing downstream of memory may see it.
check(
  "the flight controller never sees memory",
  !/memory|companion/i.test(flight),
);
check(
  "the animation layer never sees memory",
  !/memory|companion/i.test(
    read("src/components/butterfly/Butterfly.tsx") + read("src/lib/animation.ts"),
  ),
);
{
  const desktopModules = [
    "src/lib/desktop/geometry.ts",
    "src/lib/desktop/cursor.ts",
    "src/lib/desktop/hittest.ts",
    "src/lib/desktop/windows.ts",
    "src/lib/desktop/refresh.ts",
    "src/lib/desktop/environment.ts",
    "src/lib/desktop/drag.ts",
    "src/lib/desktop/window.ts",
  ]
    .map((file) => read(file))
    .join("\n");
  check(
    "desktop modules never see memory",
    !/from\s+"[^"]*memory/.test(desktopModules),
  );
}
// Interaction reports upward through a callback prop only.
check(
  "interaction does not import memory (callback prop only)",
  !/memory|companion/i.test(interaction) && /onSummon\?/.test(interaction),
);
// The personality consumes an abstract state type and nothing else.
check(
  "personality imports only the CompanionState type from memory",
  /import type \{ CompanionState \} from "\.\/memory\.ts";/.test(personality) &&
    !/new CompanionMemory|loadMemory|saveMemory|deriveCompanionState|localStorage/.test(
      personality,
    ),
);
// One memory instance, owned by the composition root.
{
  const constructions = (read("src/components/scene/Experience.tsx").match(
    /new CompanionMemory\(/g,
  ) ?? []).length;
  const otherConstructions = [
    "src/components/butterfly/Butterfly.tsx",
    "src/components/scene/Interaction.tsx",
    "src/lib/personality.ts",
    "src/lib/flight.ts",
  ].some((file) => /new CompanionMemory\(/.test(read(file)));
  check(
    "exactly one memory runtime exists, in the scene shell",
    constructions === 1 && !otherConstructions,
    `${constructions} in Experience`,
  );
}
// Persistence is one key in localStorage, and only memory.ts may touch it.
{
  const walk = (dir) =>
    readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
      entry.isDirectory()
        ? walk(resolve(dir, entry.name))
        : /\.(ts|tsx)$/.test(entry.name)
          ? [resolve(dir, entry.name)]
          : [],
    );
  const users = walk(resolve(root, "src"))
    .filter((file) => code(readFileSync(file, "utf8")).includes("localStorage"))
    .map((file) => file.split(/[\\/]/).pop());
  check(
    "only the memory and selection modules touch localStorage",
    users.length === 2 && users.join(",") === "memory.ts,species.ts",
    users.join(",") || "none",
  );
}
// Session lifecycle is best-effort persistence, never a guarantee it depends on.
{
  const experienceSource = read("src/components/scene/Experience.tsx");
  check(
    "memory flushes on page hide, once, and persists nothing per frame",
    (experienceSource.match(/pagehide/g) ?? []).length === 2 &&
      /companion\.flush\(\)/.test(experienceSource) &&
      !/requestAnimationFrame[\s\S]{0,200}companion|companion[\s\S]{0,200}requestAnimationFrame/.test(
        experienceSource,
      ),
  );
}

// --- Phase 15.2: one window, two profiles — the mode foundation --------------
const appModeModule = read("src/lib/appMode.ts");
const windowModeBridge = code(read("src/lib/desktop/mode.ts"));
const appSource = read("src/App.tsx");

// The mode vocabulary stays pure.
check(
  "the mode model imports nothing and knows nothing about the host",
  !/^\s*import\s/m.test(appModeModule) &&
    !/setInterval|requestAnimationFrame/.test(code(appModeModule)),
);
// The transition is one atomic native command, reached through a lazy bridge —
// never the JS window API piecemeal (which would need new capabilities and
// could leave the window half-switched).
check(
  "the window transition is the single native command",
  /invoke\("set_window_mode"/.test(windowModeBridge) &&
    !/setSize|setPosition|setAlwaysOnTop|setFullscreen|setDecorations/.test(
      windowModeBridge,
    ),
);
check(
  "the native side registers exactly the two commands",
  /generate_handler!\[foreground_window, set_window_mode\]/.test(rustSource),
);
{
  // The desktop profile must restore the overlay from a fresh work-area read.
  const desktopBranch = rustSource.slice(rustSource.indexOf('"desktop" =>'));
  const gardenBranch = rustSource.slice(
    rustSource.indexOf('"garden" =>'),
    rustSource.indexOf("_ =>"),
  );
  check(
    "the desktop profile re-reads the work area and restores the overlay",
    desktopBranch.includes("work_area()") &&
      desktopBranch.includes("set_always_on_top(true)") &&
      desktopBranch.includes("set_ignore_cursor_events(true)"),
  );
  check(
    "the garden profile becomes a normal focused interactive window",
    gardenBranch.includes("set_ignore_cursor_events(false)") &&
      gardenBranch.includes("set_always_on_top(false)") &&
      gardenBranch.includes("set_focus()"),
  );
  check(
    "unknown mode strings are rejected natively",
    /unknown window mode/.test(rustSource),
  );
}
// Still one window, still the same minimal capability set — nothing about the
// mode feature needed new permissions.
check(
  "still exactly one Tauri window (no second window for the garden)",
  conf.app.windows.length === 1,
);
check(
  "the capability set is unchanged by the mode feature",
  JSON.stringify([...capability.permissions].sort()) ===
    JSON.stringify(
      [
        "core:default",
        "core:window:allow-set-always-on-top",
        "core:window:allow-set-ignore-cursor-events",
        "core:window:allow-start-dragging",
      ].sort(),
    ),
  capability.permissions.join(","),
);
check(
  "no new runtime dependencies for the mode feature",
  JSON.stringify(Object.keys(packageJson.dependencies ?? {}).sort()) ===
    JSON.stringify(
      ["@react-three/fiber", "@tauri-apps/api", "react", "react-dom", "three"].sort(),
    ),
);
// The shared companion instances are mode-independent: created once, keyed on
// nothing modal.
{
  const experienceSource = read("src/components/scene/Experience.tsx");
  check(
    "the shared companion instances are created exactly once each",
    (experienceSource.match(/new FlightController\(/g) ?? []).length === 1 &&
      (experienceSource.match(/new Personality\(/g) ?? []).length === 1 &&
      (experienceSource.match(/new CompanionMemory\(/g) ?? []).length === 1,
  );
  check(
    "desktop-only effects are gated on the mode",
    /desktopSystemsActive\(mode\)\.environmentRefresh/.test(experienceSource) &&
      /desktopSystemsActive\(mode\)\.foregroundAwareness/.test(experienceSource),
  );
  check(
    "the garden presentation shares the existing scene layers",
    // The SkyDome is now called with an optional palette (Phase 15.5D), so this
    // matches the component's use rather than one particular JSX spelling. What
    // matters is that the garden still renders the *same* dome through the same
    // gate — not a second sky.
    (experienceSource.match(/<SkyDome/g) ?? []).length === 1 &&
      /mode === "garden"\) && \(\s*<SkyDome/.test(experienceSource) &&
      /\{!\(isDesktop \|\| mode === "garden"\)\} && \(\s*<SkyDome/.test(experienceSource) === false &&
      /mode === "garden"[\s\S]{0,120}skyTop: SCENE\.garden\.sky\.top/.test(
        experienceSource,
      ),
    "one SkyDome, same gate, garden palette passed as a prop",
  );
  check(
    "the garden's sky tones come from config, not from the component",
    /skyTop: SCENE\.garden\.sky\.top/.test(experienceSource) &&
      /skyHorizon: SCENE\.garden\.sky\.horizon/.test(experienceSource) &&
      /skyBelow: SCENE\.garden\.sky\.below/.test(experienceSource),
  );
}
// Interaction paths are mode-aware, and desktop polling is gated.
check(
  "interaction gates cursor polling and hit-testing on the mode",
  /desktopSystemsActive\(mode\)\.cursorPolling/.test(interaction) &&
    /onEnterGarden/.test(interaction),
);
// The camera rig switches framing with the mode rather than the platform.
check(
  "the camera rig is keyed on the mode, not the platform",
  /mode === "garden"/.test(read("src/components/scene/CameraRig.tsx")),
);
// Garden chrome exists only in garden mode; the desktop overlay stays UI-free.
check(
  "garden chrome renders only in garden mode",
  /mode === "garden" &&\s*\(?\s*<GardenChrome/.test(appSource),
);
// Nothing downstream of the mode may learn about it: the companion core stays
// mode-agnostic.
check(
  "the companion core never branches on the mode",
  !/garden|appMode|app_mode/i.test(flight) &&
    !/garden|appMode|app_mode/i.test(code(read("src/lib/personality.ts"))) &&
    !/garden|appMode|app_mode/i.test(code(read("src/lib/memory.ts"))) &&
    !/garden|appMode|app_mode/i.test(awareness),
);

// --- Phase 15.3: the garden world is scenery, built from primitives -----------
const gardenLayoutModule = read("src/lib/garden.ts");
const gardenWorld = code(read("src/components/garden/GardenWorld.tsx"));

// The layout is pure data: no host, no renderer, no behaviour.
check(
  "the garden layout imports nothing and renders nothing",
  !/^\s*import\s/m.test(gardenLayoutModule) &&
    !/three|react|@tauri-apps/.test(code(gardenLayoutModule)),
);
// The world is mounted only in garden mode — desktop stays butterfly-only.
{
  const experienceSource = read("src/components/scene/Experience.tsx");
  check(
    "the garden world renders only in garden mode",
    /mode === "garden" && <GardenWorld/.test(experienceSource),
  );
}
// Every colour and every placement comes from the config: the component holds
// no tuning of its own.
check(
  "the garden world carries no hard-coded palette",
  !/#[0-9a-fA-F]{6}/.test(gardenWorld) &&
    /SCENE\.garden/.test(gardenWorld),
);
// Primitives only: no loaders, no assets, no textures were added.
check(
  "no external assets were introduced for the garden",
  !/useGLTF|TextureLoader|loadAsync|GLTFLoader/.test(gardenWorld),
);
{
  const assets = readdirSync(resolve(root, "public", "assets")).sort();
  check(
    "the asset folder holds exactly the known butterfly GLBs",
    assets.join(",") ===
      "animated_butterfly.glb,clown_butterfly.fixed.glb,clown_butterfly.glb,ulysses_butterfly.fixed.glb",
    assets.join(","),
  );
  check(
    "the default butterfly asset is still the original GLB",
    /url: "\/assets\/animated_butterfly\.glb"/.test(read("src/config/experience.ts")) &&
      /id: "classic", name: "Existing Butterfly", asset: BUTTERFLY_ASSET/.test(
        read("src/config/experience.ts"),
      ),
  );
}
// The world never reaches into the companion: no flight, personality, memory.
check(
  "the garden world is scenery (no companion system is touched)",
  !/flight|personality|memory|companion|seekTo|notice|aimAt/i.test(gardenWorld),
);
// The layout RNG is world-building only: behaviour never imports it.
check(
  "the layout scatter is never used by the companion core",
  !/garden\.ts/.test(flight) &&
    !/garden\.ts/.test(code(read("src/lib/personality.ts"))) &&
    !/garden\.ts/.test(code(read("src/lib/memory.ts"))),
);

// --- Phase 15.4: garden interaction rides the existing public surface -------
{
  // Flower picking happens inside the one existing click path, gated to
  // garden mode, and the response uses only the same public flight surface
  // any click uses — never controller internals.
  const calls = [...interaction.matchAll(/flight\.(\w+)\(/g)].map((m) => m[1]);
  const allowed = new Set(["seekTo", "notice", "aimAt"]);
  check(
    "garden object response uses only the public flight surface",
    /mode === "garden"/.test(interaction) &&
      /pickGardenObject/.test(interaction) &&
      calls.every((name) => allowed.has(name)),
    [...new Set(calls)].join(","),
  );
  check(
    "the companion response to a garden object is a seekTo, not a placement",
    /investigationPoint/.test(interaction) &&
      !/flight\.position\.set|flight\.velocity|overrideTarget|hasOverride/.test(
        interaction,
      ),
  );
  // Feedback reaches the world as a prop; the world installs no event
  // handlers of its own (clicks stay in the single click path).
  check(
    "garden feedback is prop-driven (no second event path in the world)",
    !/onClick|onPointerDown|onPointerUp|onPointerMove|onPointerOver/.test(
      gardenWorld,
    ) && /feedbackPulse/.test(gardenWorld),
  );
  check(
    "interaction reporting for garden objects reuses personality and memory",
    /personality\.onClick/.test(interaction) && /onSummon\?\.\(\)/.test(interaction),
  );
  check(
    "garden interaction tuning lives in the config",
    /interact:\s*\{[^}]*radius:\s*[\d.]+[^}]*hoverOffset:\s*[\d.]+[^}]*stayMs:\s*[\d.]+[^}]*\}/.test(
      read("src/config/experience.ts"),
    ),
  );
  // 15.4 fix 1: a picked flower must actually win the click. While the
  // cursor is a live target, `trackLiveTarget` would overwrite the flower's
  // override on the next frame — so the flower path disarms it *before*
  // seeking. Fix 2: ownership is taken on EVERY pick (seekTo may refuse) and
  // released only by the controller's completion signal or a bounded hold.
  {
    const flowerBranch = interaction.slice(
      interaction.indexOf("if (picked)"),
      interaction.indexOf("if (picked)") + 900,
    );
    check(
      "the flower path disarms the live target before seeking",
      flowerBranch.indexOf("flight.aimAt(null)") >= 0 &&
        flowerBranch.indexOf("flight.aimAt(null)") < flowerBranch.indexOf("flight.seekTo"),
    );
    check(
      "the flower latch is taken on every pick, not only when a flight starts",
      /flowerFlight\.current = true;/.test(interaction) &&
        !/if \(summoned\) flowerFlight/.test(interaction),
    );
    check(
      "flower ownership releases on completion or a bounded hold",
      /flowerOwnershipEnds\(/.test(interaction) &&
        /flowerHoldUntil\.current/.test(interaction) &&
        /flight\.userTarget !== null/.test(interaction),
    );
    check(
      "an active flower interaction keeps the cursor out of aimAt",
      /else if \(!holdForFlower\) flight\.aimAt\(point\)/.test(interaction),
    );
    check(
      "the investigation point is solved against the live flight area",
      /interact\.hoverOffset,\s*flight\.area/.test(interaction),
    );
    check(
      "no temporary flower debug logging remains in the interaction path",
      !/flower-debug|FLOWER_DEBUG|flowerDebug|console\.debug/.test(interaction) &&
        !existsSync(resolve(root, "src/lib/flowerDebug.ts")),
    );
  }
}

// --- 15.4 fix 4: the garden gets its own flight volume ------------------------------
// The garden no longer inherits the desktop overlay's shallow depth slab (that
// slab is a fixed-camera trade: shallow depth keeps perspective scale constant
// so one box both stays in frame and reaches most of the work-area surface). The
// garden runs the follow rig over content several units deep, so its volume
// comes from its own configured content — solved by a pure airspace helper and
// applied through the existing setArea path, while the desktop solve, the
// shared bands and the controller itself stay exactly as they were.
{
  const airspace = read("src/lib/airspace.ts");

  check(
    "the garden flight volume is configured, not a literal in the shell",
    /flightArea:\s*\{\s*depthMargin:\s*[\d.]+\s*\}/.test(config),
  );
  check(
    "the garden volume is solved by a pure airspace helper from the garden config",
    /export function gardenFlightArea\(/.test(airspace) &&
      /export function gardenContentDepth\(/.test(airspace) &&
      /gardenContentDepth\(garden\)/.test(airspace) &&
      /garden\.flightArea\.depthMargin/.test(airspace),
  );
  check(
    "garden mode applies its own volume through the existing setArea path",
    /flight\.setArea\(gardenFlightArea\(\s*window\.innerWidth \/ window\.innerHeight,\s*SCENE\.garden\s*\)\)/.test(
      experience,
    ),
  );
  check(
    "the desktop volume is still solved from the work area",
    /flight\.setArea\(flightAreaForAspect\(area\.width \/ area\.height\)\)/.test(experience),
  );
  check(
    "no flight volume is written as a literal in the scene shell",
    !/\[\s*-?[\d.]+\s*,\s*-?[\d.]+\s*,\s*-?[\d.]+\s*\]/.test(experience) &&
      !/z:\s*-?[\d.]+/.test(experience),
  );
  check(
    "the shared desktop depth slab is unchanged",
    /z:\s*\[-0\.5,\s*0\.5\]/.test(airspace),
  );
  check(
    "the flight controller still knows nothing about the garden or the airspace",
    !/airspace/.test(flight) && !/garden/i.test(flight),
  );
  // The above-horizon depth reference has to reach past the deepest volume's
  // far wall, or moving the cursor up would walk the depth back toward the
  // camera. The camera trails the butterfly by 5.2 and the garden reaches
  // -3.9, so anything under ~11.8 units can reverse inside the garden.
  const reach = Number(/maxRayDistance:\s*([\d.]+)/.exec(config)?.[1] ?? 0);
  check(
    "the above-horizon depth reference reaches past the deepest garden volume",
    reach >= 12,
    `maxRayDistance=${reach} (needs > 11.7 to clear camera z 7.8 -> far wall -3.9)`,
  );
}

// --- The post-arrival stay for a successful flower flight ------------------------
// Arriving at a flower earns a short stay before the cursor takes over again.
// It must be a clock of its own, armed by the controller's completion signal
// (never by the click), entirely separate from the refusal hold, and it must
// not become a second interaction system: no new mode, no attraction loop.
{
  const gardenLayer = read("src/lib/garden.ts");

  check(
    "the post-arrival stay is configured, not a literal in the interaction",
    /FLOWER_STAY_MS = SCENE\.garden\.interact\.stayMs/.test(interaction) &&
      /stayMs:\s*\d+/.test(config),
  );
  check(
    "the stay clock is armed by arrival, not by the click",
    /flowerHadFlight\.current &&\s*flight\.userTarget === null &&\s*flowerStayUntil\.current === 0/.test(
      interaction,
    ) && /flowerStayUntil\.current = 0;/.test(interaction),
  );
  check(
    "the stay is garden-only and gated on ownership",
    /mode === "garden" &&\s*flowerFlight\.current &&\s*flowerHadFlight\.current/.test(interaction) &&
      /const holdForFlower = mode === "garden" && flowerFlight\.current/.test(interaction),
  );
  check(
    "the refusal hold is unchanged and stays a separate concept",
    /const FLOWER_HOLD_MS = 1500;/.test(interaction) &&
      /const FLOWER_STAY_MS =/.test(interaction) &&
      /flowerHoldUntil\.current = performance\.now\(\) \+ FLOWER_HOLD_MS;/.test(interaction) &&
      /flowerStayUntil\.current = now \+ FLOWER_STAY_MS;/.test(interaction),
  );
  check(
    "the ownership rule tells a flight in progress from an arrival",
    /if \(!startedFlight\) return holdExpired;/.test(gardenLayer) &&
      /if \(explicitFlightActive\) return false;/.test(gardenLayer) &&
      /return stayExpired;/.test(gardenLayer),
  );
  check(
    "a new explicit click still supersedes the flower and clears its stay",
    /flowerFlight\.current = false;\s*\n\s*flowerStayUntil\.current = 0;/.test(interaction),
  );
  check(
    "the stay introduced no second interaction path, mode or timer",
    !/setTimeout|setInterval|requestAnimationFrame/.test(interaction) &&
      !/staying|flowerStayMode/.test(interaction),
  );
}

// --- 16: the mini-game foundation ------------------------------------------------------
// A mini-game borrows the companion and returns it. These gates pin the two seams
// that make that safe: the narrow flight surface (two verbs, no internals) and the
// interaction ownership flag (one check, garden-only). Everything else about the
// foundation is asserted deterministically by tools/test-minigame.mjs; what cannot
// be asserted there is the *shape* of the boundary in the source.
{
  const minigameLayer = code(read("src/lib/minigame.ts"));
  const interactionCode = code(read("src/components/scene/Interaction.tsx"));
  const experienceCode = code(read("src/components/scene/Experience.tsx"));

  check(
    "the mini-game layer is pure: no rendering, DOM, host or persistence imports",
    importsOf(read("src/lib/minigame.ts")).every((specifier) =>
      /^(three|\.\/flight)$/.test(specifier),
    ) &&
      !/localStorage|document\.|window\.|invoke\(|fetch\(|setTimeout|setInterval|requestAnimationFrame/.test(
        minigameLayer,
      ),
    importsOf(read("src/lib/minigame.ts")).join(","),
  );
  check(
    "the mini-game layer contains no game logic (definitions live elsewhere)",
    !/\b(rings?|catch|chase|feeding?|collect|scoring|rewards?)\b/i.test(minigameLayer),
    "the runtime is a lifecycle boundary, nothing more",
  );
  check(
    "interaction checks exactly one ownership flag, and only in garden mode",
    /minigame\?\.ownsPointer\(\)/.test(interactionCode) &&
      /mode === "garden" && minigame\?\.ownsPointer\(\)/.test(interactionCode),
  );
  check(
    "the mini-game owns clicks before the flower path is consulted",
    interactionCode.indexOf("minigame.handleClick(point,") > 0 &&
      interactionCode.indexOf("minigame.handleClick(point,") <
        interactionCode.indexOf("pickGardenObject("),
    "game first, flowers second — never both",
  );
  check(
    "the mini-game surface is built over the controller, not inside it",
    /export function miniGameFlightSurface\(/.test(minigameLayer) &&
      /flight\.seekTo\(point\)/.test(minigameLayer) &&
      /flight\.aimAt\(point\)/.test(minigameLayer) &&
      !/overrideTarget|liveTarget|pickDestination|this\.velocity|this\.position\.copy/.test(
        minigameLayer,
      ),
    "two verbs, no internals",
  );
  check(
    "the flight controller exposes exactly one new mini-game seam",
    /setAutonomySuppressed\(suppressed: boolean\)/.test(code(read("src/lib/flight.ts"))) &&
      /get isAutonomySuppressed\(\)/.test(code(read("src/lib/flight.ts"))) &&
      (code(read("src/lib/flight.ts")).match(/!this\.autonomySuppressed/g) ?? []).length === 2,
    "one setter + one read-only flag, gating exactly the rhythm and the shy hop",
  );
  check(
    "the runtime is constructed once in the scene shell with both seams",
    /new MiniGameRuntime\(\{[\s\S]*?flight: miniGameFlightSurface\(flight\)[\s\S]*?setAutonomySuppressed/.test(
      experienceCode,
    ) && /<Interaction[\s\S]*?minigame=\{minigame\}/.test(experienceCode),
  );
  check(
    "no second camera system was introduced for mini-games",
    !/MiniGameCamera|minigame.*camera|camera.*minigame/i.test(minigameLayer),
  );
  check(
    "no second interaction system, memory path or personality was introduced",
    !/\b(MiniGamePersonality|MiniGameFlightController|MiniGameButterfly|MiniGameMemory)\b/i.test(
      [minigameLayer, interactionCode, experienceCode].join("\n"),
    ) && !/recordSummon|CompanionMemory|localStorage/.test(minigameLayer),
  );
  check(
    "the desktop desktop module knows nothing about mini-games",
    !/minigame/i.test(
      [
        read("src/lib/desktop/geometry.ts"),
        read("src/lib/desktop/environment.ts"),
        read("src/lib/desktop/cursor.ts"),
        read("src/lib/desktop/window.ts"),
      ].join("\n"),
    ),
  );
}

// --- 16.1: Butterfly Chase -------------------------------------------------------------
// The first game must be exactly as small as it claims: one definition file that
// reads the foundation's seams and nothing else, one marker, one HUD. These gates
// pin the boundary so a second system cannot quietly appear under the first game.
{
  const chase = code(read("src/lib/butterflyChase.ts"));
  const chaseMarker = code(read("src/components/garden/ChaseTargetMarker.tsx"));
  const chaseHud = code(read("src/components/garden/ChaseHud.tsx"));
  const experienceCode = code(read("src/components/scene/Experience.tsx"));
  const interactionSource = code(read("src/components/scene/Interaction.tsx"));

  check(
    "the chase definition is pure and imports only the foundation",
    importsOf(read("src/lib/butterflyChase.ts")).every((specifier) =>
      /^(three|\.\/flight|\.\/minigame)$/.test(specifier),
    ) &&
      !/Math\.random|localStorage|document\.|window\.|setTimeout|setInterval|Date\.now|performance\.now/.test(
        chase,
      ),
    importsOf(read("src/lib/butterflyChase.ts")).join(","),
  );
  check(
    "the chase spawns deterministically from the garden seed",
    /mulberry32/.test(chase) &&
      /CHASE_SEED_OFFSET/.test(chase) &&
      /seed \^/.test(chase),
  );
  check(
    "targets keep inside the flight area and clear of landmarks",
    /area\.min\[0\][\s\S]*area\.max\[0\]/.test(chase) &&
      /minLandmarkDistance/.test(chase),
  );
  check(
    "the chase moves the butterfly only through seekTo (no internals, no aimAt)",
    /context\.flight\.seekTo\(/.test(chase) &&
      !/context\.flight\.aimAt|overrideTarget|pickDestination|\.velocity|\.position\.copy/.test(
        chase,
      ),
  );
  check(
    "the chase hit test is the actual click ray, gated on the butterfly's arrival",
    /const along = cx \* dx \+ cy \* dy \+ cz \* dz/.test(chase) &&
      /catchable/.test(chase) &&
      /tuning\.catchRadius/.test(chase) &&
      !/scratch\.distanceTo\(point\) > tuning\.hitRadius/.test(chase),
    "ray closest-approach + catchRadius gate — not the remapped targeting point",
  );
  check(
    "the interaction layer passes the actual camera ray to the mini-game",
    /minigame\.handleClick\(point, \{\s*origin: \[camera\.position/.test(interactionSource) &&
      /unproject\(camera\)/.test(interactionSource),
  );
  check(
    "a completed game leaves no live target",
    /onStop\(\) \{\s*\/\/[\s\S]*?target = null;/.test(read("src/lib/butterflyChase.ts")) ||
      /onStop\(\) \{[\s\S]{0,300}target = null;[\s\S]{0,100}catchable = false;[\s\S]{0,100}lastSpawn = null;/.test(chase),
  );
  check(
    "the chase ends itself through the runtime's completion seam",
    /context\.complete\(\)/.test(chase) &&
      /elapsed >= tuning\.durationSeconds/.test(chase),
  );
  check(
    "the chase is config-driven, not tuned by literals",
    /garden\.chase/.test(read("src/components/garden/ChaseHud.tsx")) &&
      /tuning\./.test(chase) &&
      !/targetLifetimeSeconds:\s*\d/.test(chase),
  );
  check(
    "the chase marker renders only while playing, and allocates nothing per frame",
    /runtime\.currentState === "playing"/.test(chaseMarker) &&
      !/new (SphereGeometry|TorusGeometry|Color|Mesh)/.test(
        chaseMarker.replace(/useRef\(new Color/g, ""),
      ),
  );
  check(
    "the chase HUD starts through the runtime, never by reaching into it",
    /runtime\.start\(/.test(chaseHud) &&
      /runtime\.cancel\(/.test(chaseHud) &&
      !/\.state =|\.game =|\.transition|teardown/.test(chaseHud),
  );
  check(
    "the chase is wired into the scene shell exactly once, garden-only",
    (experienceCode.match(/ChaseTargetMarker runtime=\{minigame\}/g) ?? []).length === 1 &&
      (experienceCode.match(/ChaseHud runtime=\{minigame\} flight=\{flight\}/g) ?? []).length === 1 &&
      /mode === "garden" && <ChaseTargetMarker/.test(experienceCode) &&
      /mode === "garden" && <ChaseHud/.test(experienceCode),
  );
  check(
    "the runtime's clock is driven from exactly one frame tick",
    (experienceCode.match(/minigame\.update\(/g) ?? []).length === 1 &&
      /Math\.min\(dt, 1 \/ 20\)/.test(experienceCode),
  );
  check(
    "the chase introduced no new dependency",
    !/matter-js|planck|box2d|gsap|zustand|jotai|redux/i.test(read("package.json")),
  );
}

// --- 15.5A: the garden's own visual foundation -------------------------------------
// The garden gets a real clearing, its own atmosphere, its own light and its own
// framing — all of it beside the shared presentation, never through it. The
// desktop overlay must be able to keep rendering exactly what it rendered
// before, which is what these gates protect.
{
  const gardenLayer = read("src/lib/garden.ts");
  const gardenLight = read("src/components/garden/GardenLight.tsx");
  const cameraRig = read("src/components/scene/CameraRig.tsx");
  const groundPlane = read("src/components/scene/Ground.tsx");
  const forms = code(read("src/components/garden/gardenGeometry.ts"));
  const plantingView = read("src/components/garden/GardenPlanting.tsx");
  const backdropView = read("src/components/garden/GardenBackdrop.tsx");
  const gardenChrome = read("src/components/garden/GardenChrome.tsx");
  const skyDome = read("src/components/scene/SkyDome.tsx");
  // The shared desktop/web palette, pinned: the garden got its own sky in
  // 15.5D, and the strongest possible statement that it did not touch this one
  // is its exact previous value.
  const sharedPaletteIntact =
    /skyTop: "#bcd8d6",\s*skyHorizon: "#eaf1ee",\s*skyBelow: "#f4f7f4",\s*ground: "#cfdbd4"/.test(
      config,
    ) && /fog: \{ color: "#e9f0ec", near: 6, far: 46 \}/.test(config);

  check(
    "the clearing is configured, not built from literals in the world",
    /ground:\s*\{[\s\S]*?radius:\s*[\d.]+[\s\S]*?maxHeight:\s*[\d.]+/.test(config) &&
      /clearingMesh\(garden\.ground/.test(gardenWorld),
  );
  check(
    "the clearing is solved by the pure layout module, not the renderer",
    /export function clearingMesh\(/.test(gardenLayer) &&
      /export function groundHeight\(/.test(gardenLayer) &&
      /bufferAttribute/.test(gardenWorld) &&
      // No terrain arithmetic in the component: relief, the bank profile and the
      // boundary are all solved upstream. (The pre-existing petal ring uses
      // cos/sin; that is flower geometry, not ground.)
      !/smoothstep|hypot|edgeJitter|relief|bank\.height|edgeRadius/.test(gardenWorld),
    "geometry arithmetic stays in lib/garden.ts; the component only maps arrays",
  );
  check(
    "the flat patch disc is gone, replaced by the clearing",
    !/circleGeometry/.test(gardenWorld) && !/patch\./.test(gardenWorld) && !/patch:/.test(config),
  );
  check(
    "the ground relief can never reach the flight volume",
    Number(/maxHeight:\s*([\d.]+)/.exec(config)?.[1] ?? 99) <= 0.12,
    `maxHeight=${/maxHeight:\s*([\d.]+)/.exec(config)?.[1]} of a 0.6 flight floor`,
  );
  check(
    "the garden's relief and colours are baked, not textured",
    /vertexColors/.test(gardenWorld) && !/TextureLoader|texture=|new CanvasTexture/.test(gardenWorld),
  );
  check(
    "the garden brings its own fog, and the shared fog still exists",
    /fog:\s*\{[^}]*near:\s*[\d.]+,\s*far:\s*[\d.]+\s*\}/.test(config) &&
      /SCENE\.garden\.fog/.test(experience) &&
      /near:\s*6,\s*far:\s*46/.test(config),
    "the shared fog (6/46) is intact; the garden overrides it by mode only",
  );
  check(
    "the garden's light is a separate component, and the shared one is kept",
    /hemisphereLight/.test(gardenLight) &&
      /directionalLight/.test(gardenLight) &&
      /castShadow=\{light\.key\.castShadow\}/.test(gardenLight) &&
      /mode === "garden" \? <GardenLight \/> : <Atmosphere \/>/.test(experience),
  );
  check(
    "the garden declares a single, bounded shadow caster",
    (code(gardenLight).match(/castShadow=\{/g) ?? []).length === 1 &&
      /shadow-mapSize-width=\{light\.key\.shadowMapSize\}/.test(gardenLight) &&
      Number(/shadowMapSize:\s*(\d+)/.exec(config)?.[1] ?? 2048) <= 1024,
  );
  check(
    "the garden lights nothing on the desktop",
    /isDesktop/.test(experience) &&
      !/GardenLight/.test(read("src/components/scene/Atmosphere.tsx")),
  );
  check(
    "the shared ground plane only gained an optional colour",
    /color = SCENE\.palette\.ground/.test(groundPlane) &&
      /circleGeometry/.test(groundPlane) &&
      /colors\.surround/.test(experience),
  );
  check(
    "the garden framing is configured separately from the desktop camera",
    /camera:\s*\{[\s\S]*?offset:[\s\S]*?lookAtDrop:[\s\S]*?travel:/.test(config) &&
      /SCENE\.garden\.camera\.offset/.test(cameraRig) &&
      /position:\s*\[\s*0\.9,\s*2\.5,\s*5\.2\s*\]/.test(config) &&
      /lookAt:\s*\[\s*0,\s*1\.25,\s*0\s*\]/.test(config),
    "SCENE.camera is untouched; the garden reads its own numbers",
  );
  check(
    "the garden still uses the shared follow-camera architecture",
    /new CameraRig\(/.test(cameraRig) &&
      /framing: "fixed" as const/.test(cameraRig) &&
      !/OrbitControls|useFrame\(.*camera\.position\.(set|add)/.test(cameraRig),
  );
  check(
    "the garden's ground height never feeds flight, targeting or interaction",
    !/groundHeight|clearingMesh/.test(read("src/lib/flight.ts")) &&
      !/groundHeight|clearingMesh/.test(read("src/components/scene/Interaction.tsx")) &&
      !/groundHeight|clearingMesh/.test(read("src/lib/targeting.ts")),
  );
  check(
    "the ground relief is never built from angular harmonics (15.5A.1)",
    /function valueNoise2D\(/.test(gardenLayer) &&
      /function groundNoise\(/.test(gardenLayer) &&
      /valueNoise2D\(x, z,/.test(gardenLayer) &&
      // An amplitude-weighted sum of sines in the angle is the exact shape of
      // the defect: it makes the ground an angular extrusion, so its pattern
      // runs in radial spokes and repeats at every radius.
      !/amplitude \* Math\.sin|Math\.sin\(h\.frequency|frequency \* angle/.test(gardenLayer),
    "isotropic 2D value noise, no harmonic sum in the angle",
  );
  check(
    "the relief envelope has no threshold that switches it on",
    /Math\.pow\(Math\.max\(0, t\), ground\.relief\.gradient\)/.test(gardenLayer) &&
      !/smoothstep\(ground\.relief/.test(gardenLayer),
    "a threshold ramp left the inner clearing exactly flat and ringed it",
  );
  check(
    "the clearing sits proud of the shared plane rather than on it",
    /ground\.lift/.test(gardenLayer) && /lift:\s*[\d.]+/.test(config),
    "a few millimetres of lift keeps the rim from being coplanar with the ground",
  );
  check(
    "the planting is configured, not built from literals in the components",
    /planting:\s*\{/.test(config) &&
      /clearRadius:\s*[\d.]+/.test(config) &&
      /tallInnerRadius:\s*[\d.]+/.test(config) &&
      /clusters:\s*\[/.test(config),
  );
  check(
    "planting placement is solved by the pure layout module",
    /export function scatterLeaves\(/.test(gardenLayer) &&
      /export function scatterSeedHeads\(/.test(gardenLayer) &&
      /export function scatterFoliage\(/.test(gardenLayer) &&
      /densityAt\(/.test(gardenLayer),
    "density gradient + hand-placed clusters, decided upstream",
  );
  check(
    "the garden world stays a renderer: one instanced draw per planting family",
    (plantingView.match(/<Instances/g) ?? []).length === 4 &&
      /instancedMesh/.test(plantingView) &&
      /setColorAt/.test(plantingView),
    "four families, four draws, per-instance tone",
  );
  check(
    "every procedural garden form is generated, not imported",
    /export function bladeGeometry/.test(forms) &&
      /export function seedHeadGeometry/.test(forms) &&
      /export function pebbleGeometry/.test(forms) &&
      /export function branchGeometry/.test(forms) &&
      /export function daisyGeometry/.test(forms) &&
      !/GLTFLoader|useGLTF|TextureLoader|\.png|\.glb|\.jpg/.test(forms),
  );
  check(
    "the garden world still has no input handling",
    !/onClick|onPointerDown|onPointerUp|onPointerMove|onPointerOver/.test(
      read("src/components/garden/GardenPlanting.tsx"),
    ) && !/onClick|onPointer/.test(read("src/components/garden/gardenGeometry.ts")),
  );
  check(
    "the garden world draws its turf only through the planting module",
    !/coneGeometry/.test(gardenWorld) &&
      !/scatterGrass/.test(gardenWorld) &&
      /<GardenPlanting\s*\/>/.test(gardenWorld),
    "no leftover cone grass: the turf is the planting family's job",
  );
  check(
    "the garden world places no hooks inside a loop or a closure",
    !/\.map\([^)]*=>/.test(gardenWorld) && !/=>\s*\{\s*\n\s*const \w+ = use(Memo|Effect|Ref)/.test(gardenWorld),
  );
  // --- The far boundary and the garden's own sky (Phase 15.5D) ------------
  check(
    "the shared desktop/web palette and fog are untouched",
    sharedPaletteIntact,
    "SCENE.palette and SCENE.fog keep their exact 15.5A values",
  );
  check(
    "the garden's sky is its own, and comes from config",
    /sky: \{ top: string; horizon: string; below: string \}/.test(config) &&
      /sky: \{ top: "#[0-9a-f]{6}", horizon: "#[0-9a-f]{6}", below: "#[0-9a-f]{6}" \}/.test(
        config,
      ) &&
      // The dome takes an optional palette and defaults to the shared one, so
      // desktop and web cannot have changed behaviour even by accident.
      /palette = SCENE\.palette/.test(skyDome) &&
      /skyTop: string/.test(skyDome),
    "sky tones in config, dome unchanged for desktop/web",
  );
  check(
    "the sky and the fog meet at the horizon instead of forming a line",
    /horizon/.test(config) && /sky: \{/.test(config),
    "the far ground fades to the fog colour, so the horizon band must match it",
  );
  check(
    "the backdrop is config-driven and placed by the pure layout module",
    /backdrop: \{/.test(config) &&
      /export function scatterBackdropMounds\(/.test(gardenLayer) &&
      /export function scatterBackdropSpires\(/.test(gardenLayer) &&
      /GardenBackdrop/.test(gardenWorld),
  );
  check(
    "the backdrop costs two instanced draws and casts no shadow",
    (backdropView.match(/<Silhouettes/g) ?? []).length === 2 &&
      /instancedMesh/.test(backdropView) &&
      !/castShadow/.test(backdropView) &&
      !/receiveShadow/.test(backdropView),
    "two draws, no shadow caster spent on the darkest part of the frame",
  );
  check(
    "the backdrop geometry is generated, not imported, and stays tiny",
    /export function backdropMoundGeometry/.test(forms) &&
      /export function backdropSpireGeometry/.test(forms) &&
      !/GLTFLoader|useGLTF|TextureLoader|\.png|\.glb/.test(forms) &&
      !/Math\.random/.test(forms),
  );
  check(
    "the backdrop adds no interaction, lighting or post-processing",
    !/onClick|onPointer|useFrame|useThree/.test(backdropView) &&
      !/EffectComposer|bloom|SSAO|vignette|DepthOfField/.test(backdropView),
  );
  check(
    "the garden no longer advertises itself as a prototype",
    !/first look|prototype|preview|WIP|TODO/i.test(code(gardenChrome)) &&
      /Esc to leave/.test(gardenChrome) &&
      /Back to desktop/.test(gardenChrome),
    "the chrome states how to leave, and nothing else",
  );
  check(
    "15.5D added no dependency",
    !/postprocessing|three-stdlib|drei|maath|stats/i.test(read("package.json")),
  );
  check(
    "the stones are no longer flat-shaded primitives",
    !/flatShading|icosahedronGeometry/.test(gardenWorld) &&
      /pebbleGeometry/.test(gardenWorld),
  );
  check(
    "no scene generation uses Math.random",
    !/Math\.random/.test(gardenLayer) &&
      !/Math\.random/.test(forms) &&
      !/Math\.random/.test(plantingView),
  );
  check(
    "15.5A introduced no new dependency",
    [
      ...importsOf(read("src/components/garden/GardenWorld.tsx")),
      ...importsOf(read("src/components/garden/GardenPlanting.tsx")),
      ...importsOf(read("src/components/garden/GardenLight.tsx")),
      ...importsOf(read("src/components/garden/gardenGeometry.ts")),
    ].every((specifier) => /^(react|three|@react-three\/fiber|\.\.?\/)/.test(specifier)),
    "garden modules import only react, three, R3F and the project itself",
  );
}

// --- Final phase: butterfly selection is presentation-only --------------------
// Two asset definitions in the config, one keyed remount of the model
// component, one tiny storage seam — and nothing about behaviour changes.
{
  const configSource = read("src/config/experience.ts");
  const speciesLayer = read("src/lib/species.ts");
  const butterflyView = read("src/components/butterfly/Butterfly.tsx");
  const experienceSource = read("src/components/scene/Experience.tsx");
  const appSource2 = read("src/App.tsx");
  const chrome = read("src/components/garden/GardenChrome.tsx");

  check(
    "the species list is exactly three entries in the config",
    /export const BUTTERFLY_SPECIES/.test(configSource) &&
      (configSource.match(/id: "(?:classic|ulysses|clown)"/g) ?? []).length === 3 &&
      !/butterfly_animated/i.test(configSource),
  );
  check(
    "ulysses maps only what differs: the fixed GLB, the fly clip, the 180° yaw",
    /url: "\/assets\/ulysses_butterfly\.fixed\.glb"/.test(configSource) &&
      /clips: \{ flying: "fly", hover: "fly" \}/.test(configSource) &&
      /yawOffset: Math\.PI/.test(configSource) &&
      // Same presentation contract as the default: no bespoke sizing.
      !/ULYSSES_ASSET[\s\S]{0,300}scale:/.test(configSource),
  );
  check(
    "the selection seam is pure data + a guarded one-key store",
    /SPECIES_STORAGE_KEY = "butterfly\.companion\.species"/.test(speciesLayer) &&
      !/Math\.random|Date\.now|setTimeout|setInterval|fetch\(|invoke\(/.test(speciesLayer),
  );
  check(
    "no behaviour module may read the selection",
    ["src/lib/flight.ts", "src/lib/personality.ts", "src/lib/memory.ts",
      "src/lib/minigame.ts", "src/lib/butterflyChase.ts",
      "src/components/scene/Interaction.tsx",
    ].every((file) => !/species|Species/.test(read(file))),
  );
  check(
    "the model component takes the asset as a prop and nothing else changed",
    /asset: ButterflyAssetSpec/.test(butterflyView) &&
      /useGLTF\(asset\.url\)/.test(butterflyView) &&
      /new FlightController\(/.test(experienceSource) &&
      !/species|Species/.test(read("src/lib/gltf.ts")),
  );
  check(
    "a species switch remounts only the butterfly, keyed by id",
    /<Butterfly\s+key=\{species\.id\}/.test(experienceSource),
  );
  check(
    "the selector lives in the garden chrome only; the desktop stays UI-free",
    /BUTTERFLY_SPECIES\.map/.test(chrome) &&
      /mode === "garden" && \(\s*<GardenChrome/.test(appSource2) &&
      !/BUTTERFLY_SPECIES|species/.test(read("src/components/ui/Overlay.tsx")),
  );
  check(
    "the selection is owned once, above the scene",
    (appSource2.match(/useState<ButterflySpeciesId>/g) ?? []).length === 1 &&
      /loadSpeciesId\(\)/.test(appSource2) &&
      /saveSpeciesId\(id\)/.test(appSource2),
  );
}

// --- Keep the host minimal: no native features until a phase needs them ---
check("app identifier is not the scaffold default", conf.identifier !== "com.tauri.dev", conf.identifier);

const cargo = read("src-tauri/Cargo.toml");
const deps = [...cargo.matchAll(/^([a-z0-9-]+)\s*=/gm)].map((m) => m[1]);
check(
  "Rust dependencies stay minimal",
  !deps.some((d) => ["tauri-plugin-log", "serde", "serde_json"].includes(d)),
  deps.join(", "),
);

console.log(failures ? `\n${failures} check(s) failed` : "\nall checks passed");
process.exit(failures ? 1 : 0);
